"""create document versions table

Revision ID: 335bc35e4c28
Revises: 57b4564471ce
Create Date: 2026-06-30 21:12:06.790862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335bc35e4c28'
down_revision: Union[str, Sequence[str], None] = '57b4564471ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_versions',
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('document_id', 'version')
    )
    op.create_index('ix_document_versions_tenant_id_document_id', 'document_versions', ['tenant_id', 'document_id'], unique=False)
    op.create_index('ix_document_versions_tenant_id_status', 'document_versions', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_versions_tenant_id_status', table_name='document_versions')
    op.drop_index('ix_document_versions_tenant_id_document_id', table_name='document_versions')
    op.drop_table('document_versions')
    # ### end Alembic commands ###
