"""create documents table

Revision ID: 57b4564471ce
Revises: e096276a957b
Create Date: 2026-06-30 21:01:54.515991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b4564471ce'
down_revision: Union[str, Sequence[str], None] = 'e096276a957b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_system', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index('ix_documents_tenant_id_status', 'documents', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_tenant_id_status', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
