"""create document chunks and ingestion jobs tables

Revision ID: 71fb4613cf5d
Revises: 335bc35e4c28
Create Date: 2026-07-01 08:20:57.728522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71fb4613cf5d'
down_revision: Union[str, Sequence[str], None] = '335bc35e4c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('chunking_strategy_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('ix_document_chunks_tenant_id_document_id', 'document_chunks', ['tenant_id', 'document_id'], unique=False)
    op.create_index('ix_document_chunks_tenant_id_version', 'document_chunks', ['tenant_id', 'version'], unique=False)
    op.create_table('document_ingestion_jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_document_ingestion_jobs_tenant_id_document_id', 'document_ingestion_jobs', ['tenant_id', 'document_id'], unique=False)
    op.create_index('ix_document_ingestion_jobs_tenant_id_status', 'document_ingestion_jobs', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_ingestion_jobs_tenant_id_status', table_name='document_ingestion_jobs')
    op.drop_index('ix_document_ingestion_jobs_tenant_id_document_id', table_name='document_ingestion_jobs')
    op.drop_table('document_ingestion_jobs')
    op.drop_index('ix_document_chunks_tenant_id_version', table_name='document_chunks')
    op.drop_index('ix_document_chunks_tenant_id_document_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
